name: spam-xui
version: "1.0"


services:
  database:
    image: postgres:14
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - 5432:5432
    networks:
      - network-1
  backend:
    image: ge0rg25/webinar-spam-back
    depends_on:
      - database
    ports:
      - 2000:2000
    networks:
      - network-1
  fontend:
    image: ge0rg25/webinar-spam-front
    ports:
      - 80:80
    depends_on:
      - backend

networks:
  network-1: