name: spam-xui
version: "1.0"


services:
  backend:
    image: ge0rg25/webinar-spam-back:latest
    ports:
      - 2000:2000
    networks:
      - network-1
    restart: always
  fontend:
    image: ge0rg25/webinar-spam-front:latest
    ports:
      - 80:80
    depends_on:
      - backend
    restart: always

networks:
  network-1: